all:
	javac --module-path "./modules" --class-path="./classes" --add-modules javafx.controls,javafx.fxml dbp/main.java && \
	java --module-path "./modules" --class-path="./classes" --add-modules javafx.controls,javafx.fxml dbp/main.java
	

